# Generated by Django 5.1.3 on 2026-04-20 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_miles', models.FloatField(default=0)),
                ('from_location', models.CharField(blank=True, default='', max_length=255)),
                ('to_location', models.CharField(blank=True, default='', max_length=255)),
                ('off_duty_hrs', models.FloatField(default=0)),
                ('sleeper_hrs', models.FloatField(default=0)),
                ('driving_hrs', models.FloatField(default=0)),
                ('on_duty_hrs', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('current_lat', models.FloatField()),
                ('current_lng', models.FloatField()),
                ('pickup_location', models.CharField(max_length=255)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('dropoff_location', models.CharField(max_length=255)),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lng', models.FloatField()),
                ('current_cycle_used_hrs', models.FloatField(default=0)),
                ('total_miles', models.FloatField(default=0)),
                ('total_duration_hrs', models.FloatField(default=0)),
                ('route_geometry', models.JSONField(blank=True, default=dict)),
                ('driver_name', models.CharField(blank=True, default='', max_length=120)),
                ('carrier_name', models.CharField(blank=True, default='Spotter AI Transport', max_length=120)),
                ('truck_number', models.CharField(blank=True, default='', max_length=60)),
                ('trailer_number', models.CharField(blank=True, default='', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('OFF', 'Off Duty'), ('SB', 'Sleeper Berth'), ('D', 'Driving'), ('ON', 'On Duty (Not Driving)')], max_length=3)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='trips.dailylog')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.AddField(
            model_name='dailylog',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='trips.trip'),
        ),
        migrations.AlterUniqueTogether(
            name='dailylog',
            unique_together={('trip', 'date')},
        ),
    ]
